# SwiftLint Configuration for WinRun Host

included:
  - Sources
  - Tests

excluded:
  - .build
  - Package.swift

# Rules configuration
disabled_rules:
  - trailing_comma # Allow trailing commas for easier diffs
  - identifier_name # Allow short names like `x`, `y` for coordinates
  - todo # TODOs are fine in development
  - force_unwrapping # Too noisy, especially in tests
  - implicitly_unwrapped_optional # Common pattern in test setup
  - function_parameter_count # Sometimes needed for complex APIs
  - statement_position # Requires SourceKit (not available on Linux CI)

opt_in_rules:
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - last_where
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Line length - generous limits
line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

# Type body length - generous for test fixtures
type_body_length:
  warning: 400
  error: 600

# File length - generous for test files
file_length:
  warning: 600
  error: 1000

# Function body length
function_body_length:
  warning: 60
  error: 120

# Type name - allow short names like VM
type_name:
  min_length: 2
  max_length: 50

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# Nesting
nesting:
  type_level: 2
  function_level: 3

# Force cast severity (still warn, but not opted-in as error)
force_cast:
  severity: warning
# Note: print() is allowed because:
# - CLI tools legitimately use print() for user output
# - Logging module uses print() internally
# Use Logger in app/daemon code for structured logging

