# SwiftLint Configuration for WinRun Host

included:
  - Sources
  - Tests

excluded:
  - .build
  - Package.swift

# Rules configuration
disabled_rules:
  - trailing_comma  # Allow trailing commas for easier diffs
  - identifier_name  # Allow short names like `x`, `y` for coordinates

opt_in_rules:
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Line length: warning at 120, error at 200
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

# Type body length
type_body_length:
  warning: 300
  error: 500

# File length
file_length:
  warning: 400
  error: 600

# Function body length
function_body_length:
  warning: 50
  error: 100

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# Nesting
nesting:
  type_level: 2
  function_level: 3

# Force unwrapping severity
force_unwrapping:
  severity: warning

# Force cast severity
force_cast:
  severity: warning

# Custom rules
custom_rules:
  no_print_statements:
    name: "No print() statements"
    regex: "\\bprint\\s*\\("
    message: "Use Logger instead of print()"
    severity: warning
    match_kinds:
      - identifier

