import Foundation
import XCTest

/// Tests that verify the Swift protocol generator produces correct output.
/// These tests help catch generator bugs before they affect the codebase.
final class GeneratorTests: XCTestCase {

    // MARK: - Generator Script Existence

    func testGeneratorScriptExists() throws {
        let scriptPath = try findRepoRoot().appendingPathComponent("host/Scripts/generate-protocol.swift")
        XCTAssertTrue(
            FileManager.default.fileExists(atPath: scriptPath.path),
            "Generator script should exist at host/Scripts/generate-protocol.swift")
    }

    func testProtocolDefExists() throws {
        let protocolPath = try findRepoRoot().appendingPathComponent("shared/protocol.def")
        XCTAssertTrue(
            FileManager.default.fileExists(atPath: protocolPath.path),
            "Protocol definition should exist at shared/protocol.def")
    }

    func testGeneratedFileExists() throws {
        let generatedPath = try findRepoRoot()
            .appendingPathComponent("host/Sources/WinRunSpiceBridge/Protocol.generated.swift")
        XCTAssertTrue(
            FileManager.default.fileExists(atPath: generatedPath.path),
            "Generated file should exist")
    }

    // MARK: - Generated File Content Validation

    func testGeneratedFileHasAutoGeneratedHeader() throws {
        let content = try readGeneratedFile()

        XCTAssertTrue(
            content.contains("AUTO-GENERATED FROM shared/protocol.def"),
            "Generated file should have auto-generated header")
        XCTAssertTrue(
            content.contains("DO NOT EDIT DIRECTLY"),
            "Generated file should warn against manual edits")
    }

    func testGeneratedFileContainsExpectedTypes() throws {
        let content = try readGeneratedFile()

        // Core types
        XCTAssertTrue(content.contains("public enum SpiceProtocolVersion"))
        XCTAssertTrue(content.contains("public enum SpiceMessageType"))
        XCTAssertTrue(content.contains("public struct GuestCapabilities"))
        XCTAssertTrue(content.contains("public enum MouseButton"))
        XCTAssertTrue(content.contains("public enum MouseEventType"))
        XCTAssertTrue(content.contains("public enum KeyEventType"))
        XCTAssertTrue(content.contains("public struct KeyModifiers"))
        XCTAssertTrue(content.contains("public enum DragDropEventType"))
        XCTAssertTrue(content.contains("public enum DragOperation"))
        XCTAssertTrue(content.contains("public enum SpicePixelFormat"))
        XCTAssertTrue(content.contains("public enum WindowEventType"))
        XCTAssertTrue(content.contains("public enum ClipboardFormat"))
        XCTAssertTrue(content.contains("public enum GuestProvisioningPhase"))
    }

    func testGeneratedFileContainsBackwardsCompatAliases() throws {
        let content = try readGeneratedFile()

        XCTAssertTrue(content.contains("typealias GeneratedMessageType = SpiceMessageType"))
        XCTAssertTrue(content.contains("typealias GeneratedCapabilities = GuestCapabilities"))
    }

    func testGeneratedFileHasSendableConformance() throws {
        let content = try readGeneratedFile()

        // Key types should be Sendable for async safety
        XCTAssertTrue(content.contains("SpiceMessageType") && content.contains("Sendable"))
        XCTAssertTrue(content.contains("GuestCapabilities") && content.contains("Sendable"))
    }

    // MARK: - Protocol.def Format Validation

    func testProtocolDefHasRequiredSections() throws {
        let content = try readProtocolDef()

        // All required sections should exist
        XCTAssertTrue(content.contains("[VERSION]"))
        XCTAssertTrue(content.contains("[MESSAGE_TYPES_HOST_TO_GUEST]"))
        XCTAssertTrue(content.contains("[MESSAGE_TYPES_GUEST_TO_HOST]"))
        XCTAssertTrue(content.contains("[CAPABILITIES]"))
        XCTAssertTrue(content.contains("[MOUSE_BUTTONS]"))
        XCTAssertTrue(content.contains("[MOUSE_EVENT_TYPES]"))
        XCTAssertTrue(content.contains("[KEY_EVENT_TYPES]"))
        XCTAssertTrue(content.contains("[KEY_MODIFIERS]"))
        XCTAssertTrue(content.contains("[DRAG_DROP_EVENT_TYPES]"))
        XCTAssertTrue(content.contains("[DRAG_OPERATIONS]"))
        XCTAssertTrue(content.contains("[PIXEL_FORMATS]"))
        XCTAssertTrue(content.contains("[WINDOW_EVENT_TYPES]"))
        XCTAssertTrue(content.contains("[CLIPBOARD_FORMATS]"))
        XCTAssertTrue(content.contains("[PROVISIONING_PHASES]"))
    }

    func testProtocolDefMessageRangesAreCorrect() throws {
        let content = try readProtocolDef()
        let lines = content.components(separatedBy: .newlines)

        var inHostToGuest = false
        var inGuestToHost = false

        for line in lines {
            if line.contains("[MESSAGE_TYPES_HOST_TO_GUEST]") {
                inHostToGuest = true
                inGuestToHost = false
                continue
            }
            if line.contains("[MESSAGE_TYPES_GUEST_TO_HOST]") {
                inHostToGuest = false
                inGuestToHost = true
                continue
            }
            if line.hasPrefix("[") {
                inHostToGuest = false
                inGuestToHost = false
                continue
            }

            // Check message values are in correct ranges
            if let match = line.firstMatch(of: /=\s*0x([0-9a-fA-F]+)/) {
                let hexValue = String(match.1)
                if let value = Int(hexValue, radix: 16) {
                    if inHostToGuest {
                        XCTAssertLessThan(value, 0x80, "Host→Guest message \(line) should be < 0x80")
                    }
                    if inGuestToHost {
                        XCTAssertGreaterThanOrEqual(
                            value, 0x80, "Guest→Host message \(line) should be >= 0x80")
                    }
                }
            }
        }
    }

    // MARK: - Helpers

    private func findRepoRoot() throws -> URL {
        let testFile = URL(fileURLWithPath: #file)
        var current = testFile.deletingLastPathComponent()

        // Walk up until we find shared/protocol.def
        for _ in 0..<10 {
            let protocolPath = current.appendingPathComponent("shared/protocol.def")
            if FileManager.default.fileExists(atPath: protocolPath.path) {
                return current
            }
            current = current.deletingLastPathComponent()
        }

        throw XCTSkip("Could not find repo root")
    }

    private func readGeneratedFile() throws -> String {
        let path = try findRepoRoot()
            .appendingPathComponent("host/Sources/WinRunSpiceBridge/Protocol.generated.swift")
        return try String(contentsOf: path, encoding: .utf8)
    }

    private func readProtocolDef() throws -> String {
        let path = try findRepoRoot().appendingPathComponent("shared/protocol.def")
        return try String(contentsOf: path, encoding: .utf8)
    }
}
